# Generated by Django 4.1.7 on 2023-10-19 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('fecha_servicio', models.DateField(verbose_name='Fecha servicio')),
                ('fecha_caducidad_servicio', models.DateField(verbose_name='Fecha de caducidad del servicio')),
                ('monto_descuento_servicio', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Monto de descuento del servicio')),
                ('con_sin_igv_servicio', models.BooleanField(default=False, verbose_name='Con igv')),
                ('sub_total_servicio', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Subtotal del servicio')),
                ('total_impuesto_servicio', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Total impuesto del servicio')),
                ('total_servicio', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Total servicio')),
                ('estado_servicio', models.BooleanField(default=True, verbose_name='Estado del servicio')),
                ('nota_admin_servicio', models.TextField(verbose_name='Nota administrador del servicio')),
                ('nota_cliente_servicio', models.TextField(verbose_name='Nota cliente del servicio')),
                ('terminos_condiciones_servicio', models.TextField(verbose_name='Terminos y condiciones del servicio')),
                ('monto_descuento_oficial', models.DecimalField(decimal_places=1, max_digits=10, verbose_name='Monto de descuento oficial')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.empresa', verbose_name='Empresa')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.sede', verbose_name='Sede')),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.servicio', verbose_name='Servicio')),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_creation', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['id'],
            },
        ),
    ]
